# These are supported funding model platforms

github: [kelvingraddick]
patreon: # Replace with a single Patreon username
ko_fi: kgcodes
custom: ['https://cash.app/$kgcodes', 'https://venmo.com/u/kelvingraddick', 'https://www.paypal.com/biz/profile/100kelvins']
